# Generated by Django 2.1.3 on 2018-12-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=6)),
                ('availability', models.CharField(max_length=6)),
                ('foodimage', models.ImageField(blank=True, upload_to='restaurant/food')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=6)),
                ('restimage', models.ImageField(blank=True, upload_to='restaurant/rest')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='restaurantitems',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hotel.RestaurantLog'),
        ),
    ]
