# Generated by Django 2.1.3 on 2018-12-08 09:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=12)),
                ('deliveryid', models.CharField(max_length=12)),
                ('foodname', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=4)),
                ('price', models.CharField(max_length=5)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=150)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurantid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hotel.RestaurantLog')),
            ],
        ),
    ]
