# Generated by Django 2.1.3 on 2018-12-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='restaurantid',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
