# Generated by Django 2.1.3 on 2018-11-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('userlocation', models.CharField(max_length=150)),
                ('ordernumber', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='orderscarrying',
            old_name='driverid',
            new_name='driverids',
        ),
    ]
