# Generated by Django 2.1.3 on 2018-11-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0002_auto_20181112_0456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usersinfo',
        ),
        migrations.RenameField(
            model_name='presentlocation',
            old_name='driverid',
            new_name='driverid1',
        ),
    ]
