# Generated by Django 2.1.3 on 2018-11-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0003_auto_20181115_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('currlocation', models.CharField(max_length=150)),
                ('lastupdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=150)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpstrack.Driver')),
            ],
        ),
        migrations.DeleteModel(
            name='orderscarrying',
        ),
        migrations.DeleteModel(
            name='presentlocation',
        ),
    ]
