# Generated by Django 2.1.3 on 2018-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0005_auto_20181207_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='userINfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('orderid', models.CharField(max_length=30)),
            ],
        ),
    ]
