# Generated by Django 2.1.3 on 2018-12-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0003_auto_20181212_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('deliveryid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lat', models.FloatField(max_length=30)),
                ('long', models.FloatField(max_length=30)),
                ('lastupdate', models.DateTimeField()),
                ('restid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hotel.RestaurantLog')),
            ],
        ),
    ]
