# Generated by Django 2.1.3 on 2018-12-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0002_auto_20181212_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='deliveryid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
