# Generated by Django 2.1.3 on 2018-12-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0006_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userINfo',
            new_name='usInfo',
        ),
    ]
