# Generated by Django 2.1.3 on 2018-12-08 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0007_auto_20181208_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usInfo',
            new_name='userdet',
        ),
    ]
