# Generated by Django 2.1.3 on 2018-12-08 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20181208_1601'),
        ('gpstrack', '0008_auto_20181208_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.DeleteModel(
            name='userdet',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AddField(
            model_name='driver',
            name='deliveryid',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='restid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='payments.RestaurantLog'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
