# Generated by Django 2.1.3 on 2018-12-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpstrack', '0010_auto_20181208_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='deliveryid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
