# Generated by Django 2.1.2 on 2018-10-28 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20181028_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='custlog',
            name='password',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Restaurantdetails'),
        ),
    ]
