# Generated by Django 2.1.2 on 2018-10-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custlog',
            fields=[
                ('custid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=12)),
                ('item', models.CharField(max_length=5)),
                ('quantity', models.CharField(max_length=4)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Custlog')),
            ],
        ),
        migrations.CreateModel(
            name='restaurantdetails',
            fields=[
                ('restaurantid', models.AutoField(primary_key=True, serialize=False)),
                ('restaurantname', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.restaurantdetails'),
        ),
    ]
