# Generated by Django 2.1.2 on 2018-10-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20181028_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Restaurantdetails'),
        ),
    ]
