# Generated by Django 2.1.2 on 2018-11-17 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20181028_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=150)),
                ('custid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Custlog')),
                ('restaurantid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Restaurantdetails')),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Restaurantdetails'),
        ),
    ]
