# Generated by Django 2.1.2 on 2018-11-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20181117_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Restaurantdetails'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.Restaurantdetails'),
        ),
    ]
