# Generated by Django 2.1.3 on 2018-11-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20181116_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='rest',
            field=models.BooleanField(default=False),
        ),
    ]
