# Generated by Django 2.1.2 on 2018-11-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20181117_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantitems',
            name='foodimage',
            field=models.ImageField(blank=True, upload_to='restaurant/food'),
        ),
    ]
