# Generated by Django 2.1.2 on 2018-11-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliveryid',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
