# Generated by Django 2.1.2 on 2018-11-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_orders_deliveryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.CharField(default=120, max_length=5),
            preserve_default=False,
        ),
    ]
