# Generated by Django 2.1.2 on 2018-11-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantitems',
            name='category',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
