# Generated by Django 2.1.2 on 2018-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_restaurantitems_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlog',
            name='restimage',
            field=models.ImageField(blank=True, upload_to='restaurant/rest'),
        ),
    ]
