# Generated by Django 2.1.3 on 2018-12-08 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_restaurantlog_restimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
