# Generated by Django 2.1.2 on 2018-11-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=12)),
                ('foodname', models.CharField(max_length=150)),
                ('quantity', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=150)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.CustomerLog')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=6)),
                ('availability', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='restaurantitems',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.RestaurantLog'),
        ),
        migrations.AddField(
            model_name='orders',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.RestaurantLog'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='customerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.CustomerLog'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='restaurantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.RestaurantLog'),
        ),
    ]
