# Generated by Django 2.1.2 on 2018-11-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='foodname',
            field=models.CharField(default='buylater', max_length=150),
        ),
    ]
