# Generated by Django 2.1.2 on 2018-11-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20181117_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='status',
            field=models.CharField(default='buylater', max_length=50),
        ),
        migrations.AlterField(
            model_name='customercart',
            name='foodname',
            field=models.CharField(max_length=150),
        ),
    ]
