# Generated by Django 2.1.2 on 2018-10-15 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass1', models.FloatField()),
                ('position1', models.FloatField()),
                ('mass2', models.FloatField()),
                ('position2', models.FloatField()),
                ('com', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('userlogid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='equationlog',
            name='userlogid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='force.UserLog'),
        ),
    ]
